prompts = {
    "English": {
        "prompt": "Please enter the postal code of your return address below:",
        "enter_button": "Submit",
        "error_message": "Invalid postal code. Please try again.",
        "weather_prompt": "Current Weather Conditions",
        "weather_station": "Weather Station",
        "weather": "Weather",
        "temperature": "Temperature",
        "feels_like": "Feels Like",
        "humidity": "Humidity",
        "wind_speed": "Wind Speed",
        "wind_direction": "Wind Direction",
        "choose_route": "Choose a Route Type",
        "public_transport": "Select Public Transport Mode",
        "max_walk": "Max Walk Distance (meters)",
        "fare": "Fare",
        "total_duration": "Total Duration",
        "transit_details": "Transit Details",
        "mode": "Mode",
        "route": "Route",
        "agency": "Agency",
        "total_time": "Total Time",
        "total_distance": "Total Distance",
        "return_home": "Return Home",
        "return_home_time": "Return Home Time",
        "transit_steps": "Steps to get home",
        "restart_btn": "Restart",
        "dengue_warning": "⚠️ Warning: Red zones on the map indicate dengue cluster areas. Please take precautions.",
        "no_dengue_warning": "No dengue clusters found in your vicinity.",
        "choose_location": "Choose Location Type",
        "select_park": "Select a Park",
        "select_theme": "Select a Theme Location",
        "select_route": "Select a Route Type",
        "select_transport_mode": "Select Public Transport Mode",
        "max_walk_distance": "Max Walk Distance (meters)",
        "return_home_btn": "Return Home",
        "minutes": "minutes",
        "hours": "hours",
        "general_route_error": "Failed to generate route or route geometry missing.",
        "public_transport_error": "No valid public transport route found.",
        "steps_home": "Steps to get home"
    },
    "Malay": {
        "prompt": "Sila masukkan kod pos alamat pulang anda di bawah:",
        "enter_button": "Hantar",
        "error_message": "Kod pos tidak sah. Sila cuba lagi.",
        "weather_prompt": "Keadaan Cuaca Semasa",
        "weather_station": "Stesen Cuaca",
        "weather": "Cuaca",
        "temperature": "Suhu",
        "feels_like": "Rasa Seperti",
        "humidity": "Kelembapan",
        "wind_speed": "Kelajuan Angin",
        "wind_direction": "Arah Angin",
        "choose_route": "Pilih Jenis Laluan",
        "public_transport": "Pilih Mod Pengangkutan Awam",
        "max_walk": "Jarak Berjalan Maksimum (meter)",
        "fare": "Tambang",
        "total_duration": "Tempoh Keseluruhan",
        "transit_details": "Butiran Transit",
        "mode": "Mod",
        "route": "Laluan",
        "agency": "Agensi",
        "total_time": "Masa Keseluruhan",
        "total_distance": "Jarak Keseluruhan",
        "return_home": "Pulang Ke Rumah",
        "return_home_time": "Masa Pulang Ke Rumah",
        "transit_steps": "Langkah untuk pulang",
        "restart_btn": "Mulakan Semula",
        "dengue_warning": "⚠️ Amaran: Zon merah di peta menunjukkan kawasan kluster denggi. Sila ambil langkah berjaga-jaga.",
        "no_dengue_warning": "Tiada kluster denggi ditemui di kawasan anda.",
        "choose_location": "Pilih Jenis Lokasi",
        "select_park": "Pilih Taman",
        "select_theme": "Pilih Lokasi Tema",
        "select_route": "Pilih Jenis Laluan",
        "select_transport_mode": "Pilih Mod Pengangkutan Awam",
        "max_walk_distance": "Jarak Berjalan Maksimum (meter)",
        "return_home_btn": "Pulang Ke Rumah",
        "minutes": "minit",
        "hours": "jam",
        "general_route_error": "Gagal menghasilkan laluan atau geometri laluan tiada.",
        "public_transport_error": "Tiada laluan pengangkutan awam yang sah dijumpai.",
        "steps_home": "Langkah untuk pulang"
    },
    "Tamil": {
        "prompt": "தயவுசெய்து உங்கள் திரும்பும் முகவரியின் அஞ்சல் குறியீட்டை கீழே உள்ளிடவும்:",
        "enter_button": "சமர்ப்பிக்கவும்",
        "error_message": "தவறான அஞ்சல் குறியீடு. மீண்டும் முயற்சிக்கவும்.",
        "weather_prompt": "தற்போதைய காலநிலை நிலை",
        "weather_station": "காலநிலை நிலையம்",
        "weather": "காலநிலை",
        "temperature": "வெப்பநிலை",
        "feels_like": "உணரப்படுகிறது",
        "humidity": "ஈரப்பதம்",
        "wind_speed": "காற்று வேகம்",
        "wind_direction": "காற்றின் திசை",
        "choose_route": "பாதை வகையைத் தேர்வுசெய்க",
        "public_transport": "பொது போக்குவரத்து முறையைத் தேர்வுசெய்க",
        "max_walk": "அதிகபட்ச நடைதூரம் (மீட்டர்)",
        "fare": "கட்டணம்",
        "total_duration": "மொத்த கால அளவு",
        "transit_details": "இடமாற்ற விவரங்கள்",
        "mode": "முறை",
        "route": "பாதை",
        "agency": "நிறுவனம்",
        "total_time": "மொத்த நேரம்",
        "total_distance": "மொத்த தூரம்",
        "return_home": "வீட்டிற்கு திரும்பு",
        "return_home_time": "வீட்டிற்கு திரும்பும் நேரம்",
        "transit_steps": "வீட்டிற்கு திரும்ப எடுக்கும் நடைமுறைகள்",
        "restart_btn": "மீண்டும் தொடங்கு",
        "dengue_warning": "⚠️ எச்சரிக்கை: வரைபடத்தில் சிவப்பு பகுதிகள் டெங்கு குழுக்களைச் சுட்டிக்காட்டுகின்றன. தயவுசெய்து முன்னெச்சரிக்கையை எடுத்துக்கொள்ளுங்கள்.",
        "no_dengue_warning": "உங்கள் அருகில் டெங்கு குழுக்கள் எதுவும் இல்லை.",
        "choose_location": "இடத்தின் வகையைத் தேர்ந்தெடுக்கவும்",
        "select_park": "ஒரு பூங்காவைத் தேர்ந்தெடுக்கவும்",
        "select_theme": "தீம் இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்",
        "select_route": "பாதை வகையைத் தேர்ந்தெடுக்கவும்",
        "select_transport_mode": "பொது போக்குவரத்து முறையைத் தேர்ந்தெடுக்கவும்",
        "max_walk_distance": "அதிகபட்ச நடைதூரம் (மீட்டர்)",
        "return_home_btn": "வீட்டிற்கு திரும்பு",
        "minutes": "நிமிடங்கள்",
        "hours": "மணி",
        "general_route_error": "பாதையை உருவாக்க தவறிவிட்டது அல்லது பாதை கம்பீரம் இல்லை.",
        "public_transport_error": "சரியான பொதுப் போக்குவரத்து வழி இல்லை.",
        "steps_home": "வீட்டிற்கு திரும்பு நடைமுறைகள்"
    },
    "Chinese": {
        "prompt": "请在下方输入您的返程地址的邮政编码：",
        "enter_button": "提交",
        "error_message": "无效的邮政编码。请再试一次。",
        "weather_prompt": "当前天气状况",
        "weather_station": "气象站",
        "weather": "天气",
        "temperature": "气温",
        "feels_like": "体感温度",
        "humidity": "湿度",
        "wind_speed": "风速",
        "wind_direction": "风向",
        "choose_route": "选择路线类型",
        "public_transport": "选择公共交通模式",
        "max_walk": "最大步行距离（米）",
        "fare": "费用",
        "total_duration": "总持续时间",
        "transit_details": "过境详情",
        "mode": "模式",
        "route": "路线",
        "agency": "机构",
        "total_time": "总时间",
        "total_distance": "总距离",
        "return_home": "返回家",
        "return_home_time": "返回家时间",
        "transit_steps": "回家步骤",
        "restart_btn": "重新开始",
        "dengue_warning": "⚠️ 警告：地图上的红色区域表示登革热高发区。请采取预防措施。",
        "no_dengue_warning": "您附近没有发现登革热群集区。",
        "choose_location": "选择位置类型",
        "select_park": "选择一个公园",
        "select_theme": "选择一个主题位置",
        "select_route": "选择路线类型",
        "select_transport_mode": "选择公共交通模式",
        "max_walk_distance": "最大步行距离（米）",
        "return_home_btn": "返回家",
        "minutes": "分钟",
        "hours": "小时",
        "general_route_error": "生成路线失败或路线几何缺失。",
        "public_transport_error": "未找到有效的公共交通路线。",
        "steps_home": "返回家的步骤"
    }
}


themes = [
    "communityclubs",
    "libraries",
    "otherpanetworks",
    "museums",
    "pcnaccesspoints",
    "sportsgsportfacilities",
    "ccpwoutlet",
    "parkconnectorloop",
    "safracentre",
    "historicsites",
    "nparksskyrisegreenery",
    "parks"
]
