# Basic Streamlit app configuration

[server]
headless = true
port = 8501  # Default port, can be changed if needed
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1E90FF"  # Change this to any hex code for primary color
backgroundColor = "#FFFFFF"  # Background color for the app
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[logger]
level = "info"  # Set log level to 'info', 'debug', etc.
